server:
  port: 83

spring:
  application:
    name: cloud-alibaba-nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

service:
  nacos-provider-service: http://cloud-alibaba-nacos-provider