server:
  port: 8006

spring:
  application:
    name: cloud-provider-payment-consul
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/cloud-v2?serverTimezone=UTC&useUnicode=true&SSL=false
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        hostname: localhost
        service-name: ${spring.application.name}
        health-check-url: http://192.168.1.4:8006/actuator/health

mybatis:
  config-location: classpath:mybatis/mybatisConfig.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: my.lsh.cloud.entities

info:
  app.name: lsh-spring-cloud-demo-v2.0
  companyname: lsh.my
  build.artifactId: $project.artifactId$
  build.version: $project.version$