server:
  port: 3344
spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/lsh-hhh/spring-cloud-config-demo.git
          search-paths:   # 搜索目录
            - spring-cloud-config-demo
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672

# 暴露端口，用以刷新
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'