server:
  port: 80

spring:
  application:
    name: cloud-consumer-order-zk
  cloud:
    zookeeper:
      connect-string: localhost:2181

info:
  app.name: lsh-spring-cloud-demo-v2.0
  companyname: lsh.my
  build.artifactId: $project.artifactId$
  build.version: $project.version$