server:
  port: 7003

spring:
  application:
    name: cloud-eureka-server

eureka:
  instance:
    hostname: eureka7003.com # localhost
  client:
    register-with-eureka: false # 不注册到eureka
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/  # 集群
