server:
  port: 8401

spring:
  application:
    name: cloud-alibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # nacos服务注册中心的地址
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080   # sentinel配置的地址
        port: 8719  # 默认8719端口，如果被占用，会从8719 +1 扫描，直至找到未被占用的端口

management:
  endpoints:
    web:
      exposure:
        include: "*"