server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true     # 开启从服务中心动态创建路由的功能，利用微服务名称进行路由
      routes:
        - id: payment_route           # 无特定规则，但要求路由的id，唯一
#          uri: http://localhost:8001  # 被映射地址
          uri: lb://cloud-provider-payment  # 使用微服务名称进行路由
          predicates:
            - Path=/payment/get/**        # 断言，路径匹配则进行路由
#            - After=2020-03-08T 10:59:34.102+08:00[Asia/Shanghai] # 生效时间 在指定日期之后 ZonedDateTime
#            - Before=2020-03-08T 10:59:34.102+08:00[Asia/Shanghai] # 生效时间 在指定日期之前
#            - Between=2020-03-08T 10:59:34.102+08:00[Asia/Shanghai] ,  2020-03-08T 10:59:34.102+08:00[Asia/Shanghai] # 生效时间 在指定日期之内
#            - Cookie=username,zhangshuai    #Cookie是username=zhangshuai才能访问
#            - Query=username, \d+ #要有参数名称并且是正整数才能路由
#            - Method=GET  # 指定方法可访问
#            - Host=**.atguigu.com # 主机地址带指定主机名
#            - Header=X-Request-Id, \d+   #请求头中要有X-Request-Id属性并且值为整数的正则表达式

        - id: payment_route2           # 无特定规则，但要求路由的id，唯一
#          uri: http://localhost:8001  # 被映射地址
          uri: lb://cloud-provider-payment  # 使用微服务名称进行路由
          predicates:
            - Path=/payment/add/**        # 断言，路径匹配则进行路由

        - id: payment_route2           # 无特定规则，但要求路由的id，唯一
#          uri: http://localhost:8001  # 被映射地址
          uri: lb://cloud-provider-payment  # 使用微服务名称进行路由
          predicates:
            - Path=/payment/add/**        # 断言，路径匹配则进行路由

        - id: payment_route3           # 无特定规则，但要求路由的id，唯一
#          uri: http://localhost:8001  # 被映射地址
          uri: lb://cloud-provider-payment  # 使用微服务名称进行路由
          predicates:
            - Path=/payment/discovery       # 断言，路径匹配则进行路由
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: cloud-gateway-9527
    prefer-ip-address: true
