server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true     # 开启从服务中心动态创建路由的功能，利用微服务名称进行路由
      routes:
        - id: payment_route           # 无特定规则，但要求路由的id，唯一
#          uri: http://localhost:8001  # 被映射地址
          uri: lb://cloud-provider-payment  # 使用微服务名称进行路由
          predicates:
            - Path=/payment/get/**        # 断言，路径匹配则进行路由

        - id: payment_route2           # 无特定规则，但要求路由的id，唯一
#          uri: http://localhost:8001  # 被映射地址
          uri: lb://cloud-provider-payment  # 使用微服务名称进行路由
          predicates:
            - Path=/payment/add/**        # 断言，路径匹配则进行路由
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: cloud-gateway-9527
    prefer-ip-address: true
