server:
  port: 9001

spring:
  application:
    name: cloud-consumer-payment

eureka:
  client:
    register-with-eureka: false # 不注册到eureka
    fetch-registry: true  # client集群必须配
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/  # 集群
  instance:
    instance-id: spring-cloud-dept-provider-8001  # 指定服务的id
    prefer-ip-address: true # 使用ip地址注册

info:
  app.name: lsh-spring-cloud-demo-v2.0
  companyname: lsh.my
  build.artifactId: $project.artifactId$
  build.version: $project.version$