server:
  port: 8802

spring:
  application:
    name: cloud-stream-rabbitmq-consumer
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                username: guest
                password: guest
                port: 5672
      bindings:
        input:  # input为消费者
          destination: studyExchange  # 要使用的exchange名称
          content-type: application/json
          binder: defaultRabbit       # 要绑定消息
          group: consumer-B
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: cloud-stream-rabbitmq-consumer-8802
    prefer-ip-address: true
